# Generated by Django 5.2.8 on 2025-11-17 23:47

import promotions.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='INVITED', max_length=20)),
                ('join_code', models.CharField(db_index=True, default=promotions.models.generate_join_code, editable=False, max_length=12, unique=True)),
                ('payout_per_play', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_per_play', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=10)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ENDED', 'Ended')], default='DRAFT', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
